# Generated by Django 5.2.8 on 2026-04-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0015_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('visiting', 'Visiting'), ('adjoining', 'Adjoining'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('waiting', 'Waiting')], default='visiting', max_length=20),
        ),
    ]
